management:
  endpoints:
    web:
      exposure:
        include: [ 'health', 'healthcheck', 'prometheus' ]
      base-path: '/admin'
      path-mapping:
        prometheus: '/metrics'
server:
  port: 8080
  frontend:
    baseUrl: ${FRONTEND_URL}
    loginUrl: ${server.frontend.baseUrl}/login
    finishRegisterUrl: ${server.frontend.baseUrl}/finish-register
    oauth2RedirectUrl: ${server.frontend.baseUrl}/process-oauth2
    forgottenPasswordUrl: ${server.frontend.baseUrl}/forgotten-password
  backend:
    baseUrl: ${BACKEND_URL}
spring:
  config:
    import: "classpath:rate-limiter.yaml"
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    ddl-auto: none
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION} # a day
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRATION} # 7 days
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://www.googleapis.com
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
    mail:
      host: smtp.gmail.com
      port: 465
      protocol: smtps
      username: ${GMAIL_USERNAME}
      password: ${GMAIL_PASSWORD}
      properties:
        mail:
          transport:
            protocol: smtps
          smtps:
            auth: true
            starttls:
              enable: true
            timeout: 8000
application:
upload:
  directory: server/src/main/resources/static/uploads/

