management:
  endpoints:
    web:
      exposure:
        include: [ 'health', 'healthcheck', 'prometheus' ]
      base-path: '/admin'
      path-mapping:
        prometheus: '/metrics'
server:
  port: 8087
spring:
  application.name: plug-n-play
  datasource:
    url: jdbc:${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    validate-on-migrate: false
  jpa:
    ddl-auto: none
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  api-docs:
    path: /apidoc
#  swagger-ui:
#    path: /swagger-ui/index.html

